# -*- coding: utf-8 -*-
"""YoloModel.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SoFhH6UUe1WZwyNK9YRfsXgwX2SqSoeS
"""

import torch
from pathlib import Path
import cv2
import matplotlib.pyplot as plt
import numpy as np

model = torch.hub.load('ultralytics/yolov5', 'yolov5s', pretrained=True)

# Load image
img_path = '/content/Kabaddi.jpg'
img = cv2.imread(img_path)

# Check if the image is loaded properly
if img is None:
    print("Error: Image not loaded. Check the file path.")
else:
    # Convert BGR to RGB
    img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)

    # Display the image
    plt.imshow(img)
    plt.axis('off')  # Optional: to hide axis
    plt.show()

# Perform inference
results = model(img)

# Print results
results.print()  # Print results to console
results.show()   # Display results

# Get the results
detections = results.pandas().xyxy[0]  # Results as pandas dataframe

# Print detections
print(detections)

